---
driver:
  name: vagrant
  synced_folders:
      - ['test', '/backups', 'create: true', owner: "root", group: "root"]
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  policyfile: policies/chef-server.rb
  always_update_cookbooks: true
  # product_name: chef
  # product_version: 13.8.5

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
  - name: backup
    provisioner:
      named_run_list: backup
    verifier:
      inspec_tests:
        - test/integration/default
  - name: restore
    provisioner:
      named_run_list: restore
    attributes:
      mcs:
        policyfile:
          dir: '/backups'
        restore:
          file: '/backups/chef-server-backup-201809030650.tgz'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/policyfiles
  - name: policyfile
    provisioner:
      named_run_list: policyfiles
    attributes:
      mcs:
        policyfile:
          dir: '/backups'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/policyfiles
  - name: everything
    provisioner:
      named_run_list: everything
    attributes:
      mcs:
        policyfile:
          dir: '/backups'
        restore:
          file: '/backups/chef-server-backup-201809030650.tgz'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/policyfiles
